CREATE TABLE archive_status
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_archive_status PRIMARY KEY (id)
);

CREATE TABLE archive_status_history
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    archive_status_id  BIGINT,
    product_variant_id BIGINT,
    updated_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_archive_status_history PRIMARY KEY (id)
);

CREATE TABLE brand
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50),
    CONSTRAINT pk_brand PRIMARY KEY (id)
);

CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    price       DOUBLE PRECISION                        NOT NULL,
    image_path  VARCHAR(255)                            NOT NULL,
    brand_id    BIGINT,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE product_variant
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    size           VARCHAR(255)                            NOT NULL,
    material       VARCHAR(255)                            NOT NULL,
    stock          INTEGER                                 NOT NULL,
    product_id     BIGINT,
    archive_status BIGINT,
    CONSTRAINT pk_product_variant PRIMARY KEY (id)
);

ALTER TABLE brand
    ADD CONSTRAINT uc_brand_name UNIQUE (name);

ALTER TABLE archive_status_history
    ADD CONSTRAINT FK_ARCHIVE_STATUS_HISTORY_ON_ARCHIVESTATUS FOREIGN KEY (archive_status_id) REFERENCES archive_status (id);

ALTER TABLE archive_status_history
    ADD CONSTRAINT FK_ARCHIVE_STATUS_HISTORY_ON_PRODUCTVARIANT FOREIGN KEY (product_variant_id) REFERENCES product_variant (id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_BRAND FOREIGN KEY (brand_id) REFERENCES brand (id);

ALTER TABLE product_variant
    ADD CONSTRAINT FK_PRODUCT_VARIANT_ON_ARCHIVE_STATUS FOREIGN KEY (archive_status) REFERENCES archive_status (id);

ALTER TABLE product_variant
    ADD CONSTRAINT FK_PRODUCT_VARIANT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

insert into brand
values (default, 'nike');

insert into brand
values (default, 'adidas');

insert into product
values (default, 'Nike T-shirt', 'Nike tee', 120, 'https://img01.ztat.net/article/spp-media-p1/e0248edfa3bd4202a4f91a7fc40eac3c/b6822106f7444815839c1338fc9a8e93.jpg?imwidth=762&filter=packshot', 1);

insert into product
values (default, 'Adidas', 'Adidas tee', 10, 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/825d33b9f25a4a69b2baac4600ea0e04_9366/Essentials_Big_Logo_T-shirt_Sort_GK9120_01_laydown.jpg', 2);

insert into product_variant
values (default, 'M', '100% cotton', 52, 1);

insert into product_variant
values (default, 'XL', '100% cotton', 67, 1);

insert into archive_status
values (default,'Archived');

insert into archive_status
values (default, 'Active')