CREATE TABLE brand
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50),
    CONSTRAINT pk_brand PRIMARY KEY (id)
);

CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    brand_id    BIGINT,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE product_variant
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    size       VARCHAR(255),
    material   VARCHAR(255),
    stock      INTEGER                                 NOT NULL,
    product_id BIGINT,
    CONSTRAINT pk_product_variant PRIMARY KEY (id)
);

ALTER TABLE brand
    ADD CONSTRAINT uc_brand_name UNIQUE (name);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_BRAND FOREIGN KEY (brand_id) REFERENCES brand (id);

ALTER TABLE product_variant
    ADD CONSTRAINT FK_PRODUCT_VARIANT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);